import { ArrowRight, Eye, EyeOff, Lock, Plus, ShieldCheck } from 'lucide-react'
import Button from '../../../../components/ui/Button'
import { WizardCard, WizardPanel } from '../../../../components/wizard/WizardPanel'

function EnvVarsPanel({
  userSecretVars,
  generatedVars,
  secretValues,
  showSecrets,
  extraVars,
  allSecretsFilled,
  onSecretValueChange,
  onToggleSecretVisibility,
  onAddVariable,
  onExtraVariableChange,
  onContinue,
}) {
  return (
    <WizardPanel>
      <WizardCard width='lg'>
        <div>
          <h3 className='text-lg font-semibold'>Values required from you</h3>
          <p className='mt-1 text-sm text-text-muted'>These secrets are needed to run your app. Fill in each one to continue.</p>
        </div>
        <div className='mt-4 space-y-4'>
          {userSecretVars.map((field) => (
            <div key={field.key_name}>
              <div className='mb-1 flex items-center justify-between gap-3'>
                <p className='text-sm font-semibold text-text-primary'>{field.key_name}</p>
                {field.context_block ? <p className='text-xs text-text-muted'>{field.context_block}</p> : null}
              </div>
              <div className='flex gap-2'>
                <input
                  type={showSecrets[field.key_name] ? 'text' : 'password'}
                  value={secretValues[field.key_name] || ''}
                  onChange={(event) => onSecretValueChange(field.key_name, event.target.value)}
                  className='w-full rounded-lg border border-white/[0.09] bg-background px-3.5 py-2.5 text-sm text-text-primary transition-[border-color,box-shadow] duration-150 hover:border-white/[0.15] focus-visible:outline-none focus-visible:border-accent/50 focus-visible:ring-2 focus-visible:ring-accent/20'
                />
                <Button
                  variant='ghost'
                  size='sm'
                  onClick={() => onToggleSecretVisibility(field.key_name)}
                  aria-label={showSecrets[field.key_name] ? 'Hide value' : 'Show value'}
                >
                  {showSecrets[field.key_name] ? <EyeOff className='h-4 w-4' /> : <Eye className='h-4 w-4' />}
                </Button>
              </div>
            </div>
          ))}
        </div>

        <h3 className='mt-7 text-lg font-semibold'>Auto-generated by Crylo</h3>
        <p className='mt-1 text-sm text-text-muted'>Crylo creates and manages these for you — no action needed.</p>
        <div className='mt-3 space-y-2'>
          {generatedVars.map((field) => (
            <div key={field.key_name} className='flex items-center justify-between rounded-lg border border-border bg-background px-3 py-2'>
              <div>
                <p className='text-sm font-semibold text-text-primary'>{field.key_name}</p>
                {field.production_default ? <p className='text-xs text-text-muted'>{field.production_default}</p> : null}
              </div>
              <div className='flex items-center gap-2'>
                <Lock className='h-3.5 w-3.5 text-text-muted' />
                <span className='rounded-full border border-green-500/30 bg-green-500/10 px-2 py-1 text-xs text-green-300'>Auto-generated</span>
              </div>
            </div>
          ))}
        </div>

        <button
          type='button'
          className='mt-4 inline-flex items-center gap-1 text-xs text-text-muted transition-colors hover:text-text-primary disabled:opacity-40'
          disabled={extraVars.length >= 3}
          onClick={onAddVariable}
        >
          <Plus className='h-3.5 w-3.5' />
          Add variable
        </button>
        <div className='mt-2 space-y-2'>
          {extraVars.map((row, index) => (
            <div key={index} className='grid grid-cols-2 gap-2'>
              <input
                type='text'
                placeholder='KEY'
                value={row.key}
                onChange={(event) => onExtraVariableChange(index, 'key', event.target.value)}
                className='rounded-lg border border-white/[0.09] bg-background px-3.5 py-2.5 text-sm text-text-primary hover:border-white/[0.15] focus-visible:outline-none focus-visible:border-accent/50 focus-visible:ring-2 focus-visible:ring-accent/20'
              />
              <input
                type='password'
                placeholder='VALUE'
                value={row.value}
                onChange={(event) => onExtraVariableChange(index, 'value', event.target.value)}
                className='rounded-lg border border-white/[0.09] bg-background px-3.5 py-2.5 text-sm text-text-primary hover:border-white/[0.15] focus-visible:outline-none focus-visible:border-accent/50 focus-visible:ring-2 focus-visible:ring-accent/20'
              />
            </div>
          ))}
        </div>

        <p className='mt-4 flex items-start gap-1.5 text-xs text-text-muted'>
          <ShieldCheck className='mt-0.5 h-3.5 w-3.5 shrink-0 text-success' />
          Secret values are written directly to AWS Secrets Manager in your account. Crylo never stores them.
        </p>

        <Button variant='primary' className='mt-5' disabled={!allSecretsFilled} onClick={onContinue}>
          Save & continue
          <ArrowRight className='h-4 w-4' />
        </Button>
      </WizardCard>
    </WizardPanel>
  )
}

export default EnvVarsPanel
