from django.urls import path

from .canvas.views import (
    canvas_agent,
    canvas_chat,
    canvas_chat_flush,
    canvas_dismiss,
    canvas_finalize,
    canvas_latest,
    canvas_revert,
    canvas_versions,
)
from .views import (
    hello,
    connect_repo,
    github_branches,
    github_installations,
    github_repos,
    me,
    project_detail,
    projects_list,
    save_intent,
    trigger_scan,
    wizard_state,
)
from .provisioning.views import (
    aws_connection_init,
    aws_connection_verify,
    env_vars_list,
    env_vars_save,
    iac_current,
    iac_generate,
    iac_refine,
    iac_validate,
)

urlpatterns = [
    path('hello', hello),
    path('users/me/', me),
    path('projects/', projects_list),
    path('projects/<uuid:pk>/', project_detail),
    path('projects/<uuid:pk>/connect-repo/', connect_repo),
    path('projects/<uuid:pk>/scan/', trigger_scan),
    path('projects/<uuid:pk>/intent/', save_intent),
    path('projects/<uuid:pk>/wizard-state/', wizard_state),
    path('projects/<uuid:pk>/canvas/latest/', canvas_latest),
    path('projects/<uuid:pk>/canvas/agent/', canvas_agent),
    path('projects/<uuid:pk>/canvas/chat/', canvas_chat),
    path('projects/<uuid:pk>/canvas/chat/flush/', canvas_chat_flush),
    path('projects/<uuid:pk>/canvas/dismiss/', canvas_dismiss),
    path('projects/<uuid:pk>/canvas/versions/', canvas_versions),
    path('projects/<uuid:pk>/canvas/versions/<int:version_number>/revert/', canvas_revert),
    path('projects/<uuid:pk>/canvas/finalize/', canvas_finalize),
    path('projects/<uuid:pk>/aws-connection/', aws_connection_init),
    path('projects/<uuid:pk>/aws-connection/verify/', aws_connection_verify),
    path('projects/<uuid:pk>/env-vars/', env_vars_list),
    path('projects/<uuid:pk>/env-vars/save/', env_vars_save),
    path('projects/<uuid:pk>/iac/', iac_current),
    path('projects/<uuid:pk>/iac/generate/', iac_generate),
    path('projects/<uuid:pk>/iac/refine/', iac_refine),
    path('projects/<uuid:pk>/iac/validate/', iac_validate),
    path('github/installations/', github_installations),
    path('github/repos/', github_repos),
    path('github/branches/', github_branches),
]
