# Generated by Django 6.0.1 on 2026-05-31 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccountConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aws_account_id', models.TextField()),
                ('aws_region', models.TextField(default='us-east-1')),
                ('iam_role_arn', models.TextField()),
                ('bootstrap_stack_id', models.TextField(blank=True, null=True)),
                ('bootstrap_stack_status', models.TextField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aws_account_connections',
            },
        ),
        migrations.CreateModel(
            name='GitHubInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.BigIntegerField(unique=True)),
                ('account_login', models.TextField()),
                ('account_type', models.TextField(choices=[('User', 'User'), ('Organization', 'Organization')])),
                ('account_avatar_url', models.TextField(blank=True, null=True)),
                ('app_id', models.IntegerField()),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'github_installations',
            },
        ),
        migrations.CreateModel(
            name='IntentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('scale', models.TextField(blank=True, choices=[('solo', 'Solo'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], null=True)),
                ('criticality', models.TextField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], null=True)),
                ('environment', models.TextField(blank=True, choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')], null=True)),
                ('compute_choice', models.TextField(blank=True, choices=[('ecs_fargate', 'Ecs Fargate'), ('ecs_ec2', 'Ecs Ec2'), ('ec2', 'Ec2')], null=True)),
                ('database_choice', models.TextField(blank=True, choices=[('rds_postgres', 'Rds Postgres'), ('aurora_postgres', 'Aurora Postgres')], null=True)),
                ('worker_compute_choice', models.TextField(blank=True, choices=[('ecs_fargate', 'Ecs Fargate'), ('ecs_ec2', 'Ecs Ec2'), ('ec2', 'Ec2')], null=True)),
                ('domain_has', models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('internal', 'Internal')], null=True)),
                ('domain_name', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'intent_records',
            },
        ),
        migrations.CreateModel(
            name='CanvasVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft')),
                ('canvas_yaml', models.TextField()),
                ('canvas_snapshot', models.JSONField()),
                ('operation', models.TextField(blank=True, choices=[('INITIAL', 'Initial'), ('ADD_NODE', 'Add Node'), ('REMOVE_NODE', 'Remove Node'), ('UPDATE_NODE', 'Update Node'), ('ADD_CONNECTION', 'Add Connection'), ('REMOVE_CONNECTION', 'Remove Connection'), ('REVERT', 'Revert')], null=True)),
                ('changed_node_id', models.TextField(blank=True, null=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('estimated_cost', models.JSONField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canvas_versions', to='core.intentrecord')),
            ],
            options={
                'db_table': 'canvas_versions',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('created', 'Created'), ('repo_connected', 'Repo Connected'), ('scanning', 'Scanning'), ('scan_complete', 'Scan Complete'), ('intent_collected', 'Intent Collected'), ('canvas_draft', 'Canvas Draft'), ('canvas_finalized', 'Canvas Finalized'), ('provisioning', 'Provisioning'), ('live', 'Live'), ('failed', 'Failed')], default='created')),
                ('repo_full_name', models.TextField(blank=True, null=True)),
                ('repo_branch', models.TextField(default='main')),
                ('is_monorepo', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.githubinstallation')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='intentrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_records', to='core.project'),
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.TextField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')])),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('generating_iac', 'Generating Iac'), ('submitting', 'Submitting'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending')),
                ('cloudformation_stack_id', models.TextField(blank=True, null=True)),
                ('cloudformation_stack_name', models.TextField(blank=True, null=True)),
                ('cloudformation_template', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='core.awsaccountconnection')),
                ('canvas_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='core.canvasversion')),
                ('intent_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='core.intentrecord')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='core.project')),
            ],
            options={
                'db_table': 'deployments',
            },
        ),
        migrations.AddField(
            model_name='canvasversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_versions', to='core.project'),
        ),
        migrations.AddField(
            model_name='awsaccountconnection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_connections', to='core.project'),
        ),
        migrations.CreateModel(
            name='ProvisioningLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('resource_type', models.TextField(blank=True, null=True)),
                ('resource_id', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('plain_message', models.TextField()),
                ('raw_event', models.JSONField(blank=True, null=True)),
                ('event_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.deployment')),
            ],
            options={
                'db_table': 'provisioning_log_entries',
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='running')),
                ('block_reason', models.TextField(blank=True, null=True)),
                ('detected_resources', models.JSONField(blank=True, null=True)),
                ('env_vars', models.JSONField(blank=True, null=True)),
                ('draft_canvas_yaml', models.TextField(blank=True, null=True)),
                ('raw_file_tree', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='core.project')),
            ],
            options={
                'db_table': 'scan_results',
            },
        ),
        migrations.CreateModel(
            name='EnvVarKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_name', models.TextField()),
                ('classification', models.TextField(choices=[('generated', 'Generated'), ('user_secret', 'User Secret'), ('optional', 'Optional')])),
                ('source_file', models.TextField(blank=True, null=True)),
                ('context_block', models.TextField(blank=True, null=True)),
                ('production_default', models.TextField(blank=True, null=True)),
                ('secrets_manager_arn', models.TextField(blank=True, null=True)),
                ('secrets_manager_key', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_var_keys', to='core.project')),
                ('scan_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='env_var_keys', to='core.scanresult')),
            ],
            options={
                'db_table': 'env_var_keys',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cognito_sub', models.TextField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('subscription_tier', models.TextField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['cognito_sub'], name='users_cognito_fd04d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.TextField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free')),
                ('status', models.TextField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('trialing', 'Trialing')], default='active')),
                ('payment_gateway', models.TextField(blank=True, choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay')], null=True)),
                ('gateway_customer_id', models.TextField(blank=True, null=True)),
                ('gateway_sub_id', models.TextField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.user')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.user'),
        ),
        migrations.AddField(
            model_name='githubinstallation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to='core.user'),
        ),
        migrations.CreateModel(
            name='DeploymentStackOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_key', models.TextField()),
                ('output_value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_outputs', to='core.deployment')),
            ],
            options={
                'db_table': 'deployment_stack_outputs',
                'indexes': [models.Index(fields=['deployment'], name='deployment__deploym_0a9dbd_idx')],
                'unique_together': {('deployment', 'output_key')},
            },
        ),
        migrations.CreateModel(
            name='MonitoringAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.TextField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')])),
                ('source_alarm', models.TextField()),
                ('plain_message', models.TextField()),
                ('resource_type', models.TextField(blank=True, null=True)),
                ('resource_id', models.TextField(blank=True, null=True)),
                ('fired_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.deployment')),
            ],
            options={
                'db_table': 'monitoring_alerts',
                'indexes': [models.Index(fields=['deployment'], name='monitoring__deploym_1ba453_idx'), models.Index(fields=['deployment', '-fired_at'], name='monitoring__deploym_b9003d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringMetricsCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.TextField()),
                ('metric_value', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_cache', to='core.deployment')),
            ],
            options={
                'db_table': 'monitoring_metrics_cache',
                'indexes': [models.Index(fields=['deployment'], name='monitoring__deploym_31736b_idx')],
                'unique_together': {('deployment', 'metric_key')},
            },
        ),
        migrations.AddIndex(
            model_name='intentrecord',
            index=models.Index(fields=['project'], name='intent_reco_project_0c9ada_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['project'], name='deployments_project_f26084_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['project', 'status'], name='deployments_project_a4ba9c_idx'),
        ),
        migrations.AddIndex(
            model_name='canvasversion',
            index=models.Index(fields=['project'], name='canvas_vers_project_cc2a75_idx'),
        ),
        migrations.AddIndex(
            model_name='canvasversion',
            index=models.Index(fields=['project', 'status'], name='canvas_vers_project_7608f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='canvasversion',
            unique_together={('project', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='awsaccountconnection',
            index=models.Index(fields=['project'], name='aws_account_project_133227_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioninglogentry',
            index=models.Index(fields=['deployment'], name='provisionin_deploym_7e8827_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='provisioninglogentry',
            unique_together={('deployment', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['project'], name='scan_result_project_ff4599_idx'),
        ),
        migrations.AddIndex(
            model_name='envvarkey',
            index=models.Index(fields=['project'], name='env_var_key_project_743381_idx'),
        ),
        migrations.AddIndex(
            model_name='envvarkey',
            index=models.Index(fields=['project', 'classification'], name='env_var_key_project_c17b88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='envvarkey',
            unique_together={('project', 'key_name')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user'], name='subscriptio_user_id_aa8bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='projects_user_id_d4f582_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='githubinstallation',
            index=models.Index(fields=['user'], name='github_inst_user_id_758280_idx'),
        ),
    ]
