# Generated by Django 6.0.1 on 2026-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('generating_iac', 'Generating Iac'), ('iac_ready', 'Iac Ready'), ('submitting', 'Submitting'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending'),
        ),
    ]
