# Generated by Django 6.0.1 on 2026-07-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentrecord',
            name='aws_account_type',
            field=models.TextField(blank=True, choices=[('paid', 'Paid'), ('free_tier', 'Free Tier')], null=True),
        ),
    ]
