# Generated by Django 6.0.1 on 2026-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_intentrecord_aws_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='paused_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('generating_iac', 'Generating Iac'), ('iac_ready', 'Iac Ready'), ('submitting', 'Submitting'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('pausing', 'Pausing'), ('paused', 'Paused'), ('resuming', 'Resuming'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='pending'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('created', 'Created'), ('repo_connected', 'Repo Connected'), ('scanning', 'Scanning'), ('scan_complete', 'Scan Complete'), ('intent_collected', 'Intent Collected'), ('canvas_draft', 'Canvas Draft'), ('canvas_finalized', 'Canvas Finalized'), ('provisioning', 'Provisioning'), ('live', 'Live'), ('failed', 'Failed'), ('paused', 'Paused'), ('deleted', 'Deleted')], default='created'),
        ),
    ]
