# Generated by Django 6.0.1 on 2026-07-06 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deployment_paused_state_alter_deployment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.TextField(choices=[('scan', 'Scan'), ('canvas_chat', 'Canvas Chat'), ('iac_generate', 'Iac Generate'), ('iac_refine', 'Iac Refine'), ('provision', 'Provision')])),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_jobs', to='core.project')),
            ],
            options={
                'db_table': 'agent_jobs',
                'indexes': [models.Index(fields=['project', 'kind'], name='agent_jobs_project_62c686_idx')],
            },
        ),
    ]
