# Generated by Django 6.0.1 on 2026-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agentjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentjob',
            name='kind',
            field=models.TextField(choices=[('scan', 'Scan'), ('canvas_chat', 'Canvas Chat'), ('iac_generate', 'Iac Generate'), ('iac_refine', 'Iac Refine'), ('provision', 'Provision'), ('build', 'Build')]),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('generating_iac', 'Generating Iac'), ('iac_ready', 'Iac Ready'), ('submitting', 'Submitting'), ('in_progress', 'In Progress'), ('building', 'Building'), ('build_failed', 'Build Failed'), ('complete', 'Complete'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('pausing', 'Pausing'), ('paused', 'Paused'), ('resuming', 'Resuming'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='pending'),
        ),
    ]
