# Generated by Django 6.0.1 on 2026-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_agentjob_kind_alter_deployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='compliance_findings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
