# Generated by Django 6.0.1 on 2026-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_scanresult_compliance_findings'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentjob',
            name='progress',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
