# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agentjob_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.TextField(choices=[
                ('pending', 'Pending'),
                ('generating_iac', 'Generating Iac'),
                ('iac_ready', 'Iac Ready'),
                ('submitting', 'Submitting'),
                ('in_progress', 'In Progress'),
                ('building', 'Building'),
                ('build_failed', 'Build Failed'),
                ('complete', 'Complete'),
                ('failed', 'Failed'),
                ('rolling_back', 'Rolling Back'),
                ('rolled_back', 'Rolled Back'),
                ('pausing', 'Pausing'),
                ('paused', 'Paused'),
                ('resuming', 'Resuming'),
                ('deleting', 'Deleting'),
                ('deleted', 'Deleted'),
            ], default='pending'),
        ),
    ]
