# Generated by Django 6.0.1 on 2026-07-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_deployment_rolling_back_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='aws_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='core.awsaccountconnection'),
        ),
    ]
