# Generated by Django 6.0.1 on 2026-07-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_deployment_aws_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccountconnection',
            name='verified_account_type',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('free_tier', 'Free Tier')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='envvarkey',
            name='staged_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('created', 'Created'), ('repo_connected', 'Repo Connected'), ('secrets_staged', 'Secrets Staged'), ('scanning', 'Scanning'), ('scan_complete', 'Scan Complete'), ('intent_collected', 'Intent Collected'), ('canvas_draft', 'Canvas Draft'), ('canvas_finalized', 'Canvas Finalized'), ('aws_connect_pending', 'Aws Connect Pending'), ('aws_connected', 'Aws Connected'), ('aws_verified', 'Aws Verified'), ('aws_mismatch', 'Aws Mismatch'), ('iac_generated', 'Iac Generated'), ('iac_validated', 'Iac Validated'), ('provisioning', 'Provisioning'), ('live', 'Live'), ('failed', 'Failed'), ('paused', 'Paused'), ('deleted', 'Deleted')], default='created'),
        ),
    ]
