# Generated by Django 6.0.1 on 2026-07-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_awsaccountconnection_verified_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccountconnection',
            name='claimed_account_type',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('free_tier', 'Free Tier')], max_length=16, null=True),
        ),
    ]
