# Generated by Django 6.0.1 on 2026-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_awsaccountconnection_claimed_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentrecord',
            name='route53_hosted_zone_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
