# Generated by Django 6.0.1 on 2026-07-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_intentrecord_route53_hosted_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccountconnection',
            name='health_status',
            field=models.TextField(choices=[('healthy', 'Healthy'), ('unreachable', 'Unreachable'), ('unknown', 'Unknown')], default='unknown'),
        ),
        migrations.AddField(
            model_name='awsaccountconnection',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
