# Generated by Django 6.0.1 on 2026-07-18 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_awsaccountconnection_health_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stack_status', models.TextField()),
                ('healthy', models.BooleanField()),
                ('health_items', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('alerts', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='core.project')),
            ],
            options={
                'db_table': 'health_snapshots',
                'indexes': [models.Index(fields=['project', 'created_at'], name='health_snap_project_26ac80_idx')],
            },
        ),
    ]
