# Generated by Django 6.0.1 on 2026-07-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_healthsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentjob',
            name='kind',
            field=models.TextField(choices=[('scan', 'Scan'), ('canvas_chat', 'Canvas Chat'), ('iac_generate', 'Iac Generate'), ('iac_refine', 'Iac Refine'), ('provision', 'Provision'), ('build', 'Build'), ('delete', 'Delete')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('created', 'Created'), ('repo_connected', 'Repo Connected'), ('secrets_staged', 'Secrets Staged'), ('scanning', 'Scanning'), ('scan_complete', 'Scan Complete'), ('intent_collected', 'Intent Collected'), ('canvas_draft', 'Canvas Draft'), ('canvas_finalized', 'Canvas Finalized'), ('aws_connect_pending', 'Aws Connect Pending'), ('aws_connected', 'Aws Connected'), ('aws_verified', 'Aws Verified'), ('aws_mismatch', 'Aws Mismatch'), ('iac_generated', 'Iac Generated'), ('iac_validated', 'Iac Validated'), ('provisioning', 'Provisioning'), ('live', 'Live'), ('failed', 'Failed'), ('paused', 'Paused'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='created'),
        ),
    ]
