# Generated by Django 6.0.1 on 2026-07-25 06:32

import logging

from django.db import migrations, models

log = logging.getLogger(__name__)


def drop_duplicate_pending_connections(apps, schema_editor):
    """Clear the rows the aws_connection_init race already created, so the
    constraint below can be applied.

    Only NEVER-CONNECTED rows are touched — a project that successfully connected
    has connected_at set and is outside this filter entirely, so no live
    deployment can lose its credentials here. Where a project has several pending
    rows we keep the oldest: that's the one the first of the two racing requests
    created, and the one the observed stacks were actually built from. If a user
    did build their stack from the discarded id, verify now tells them so by name
    ("this role belongs to a different Clyro connection") instead of failing with
    an opaque AccessDenied, and the CloudFormation link mints a fresh stack.
    """
    AWSAccountConnection = apps.get_model('core', 'AWSAccountConnection')

    pending = AWSAccountConnection.objects.filter(connected_at__isnull=True).order_by('project_id', 'created_at')

    seen_projects = set()
    doomed = []
    for conn in pending:
        if conn.project_id in seen_projects:
            doomed.append(conn.pk)
        else:
            seen_projects.add(conn.project_id)

    if doomed:
        log.warning('0018: deleting %d duplicate pending AWS connection(s): %s', len(doomed), doomed)
        AWSAccountConnection.objects.filter(pk__in=doomed).delete()


class Migration(migrations.Migration):

    # The delete below and the CREATE UNIQUE INDEX the constraint compiles to
    # cannot share a transaction: Postgres refuses the index with "cannot CREATE
    # INDEX ... because it has pending trigger events" while the delete's
    # deferred foreign-key triggers are still outstanding. Running non-atomically
    # lets the cleanup commit first. If the constraint then failed, the deleted
    # rows stay deleted — they were unusable duplicates, so that's harmless.
    atomic = False

    dependencies = [
        ('core', '0017_adminuser_whitelistedemail'),
    ]

    operations = [
        migrations.RunPython(
            drop_duplicate_pending_connections,
            # Nothing to restore — the deleted rows were never usable.
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='awsaccountconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('connected_at__isnull', True)), fields=('project',), name='uniq_pending_connection_per_project'),
        ),
    ]
