# Generated by Django 6.0.1 on 2026-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_awsaccountconnection_uniq_pending_connection_per_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='envvarkey',
            name='acquire_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envvarkey',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='contract_drift',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='contract_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='contract_raw',
            field=models.TextField(blank=True, null=True),
        ),
        # Added as 'live' so existing rows are backfilled with the truth — every
        # scan that already exists came from the retired in-cloud scanner — then
        # altered to the model's real default so new rows are 'clyro_md'.
        # AlterField only touches the column default, not the backfilled data.
        migrations.AddField(
            model_name='scanresult',
            name='source',
            field=models.TextField(choices=[('clyro_md', 'Clyro Md'), ('live', 'Live')], default='live'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='source',
            field=models.TextField(choices=[('clyro_md', 'Clyro Md'), ('live', 'Live')], default='clyro_md'),
        ),
    ]
